# Generated by Django 5.1 on 2024-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_painting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products_images/'),
        ),
    ]
