# Generated by Django 5.1 on 2024-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_painting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
