# Generated by Django 5.1 on 2024-09-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_painting_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
    ]
