# Generated by Django 5.1 on 2024-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_painting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
