# Generated by Django 5.1 on 2024-09-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_painting_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='slug',
        ),
    ]
