# Generated by Django 5.1 on 2024-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_painting_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='slug',
        ),
        migrations.AddField(
            model_name='painting',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
    ]
