# Generated by Django 5.1 on 2024-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
