# Generated by Django 5.1 on 2025-06-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_image',
            field=models.ImageField(default=None, null=True, upload_to='bg_images/'),
        ),
    ]
